// frontend/src/components/FirebaseAuth.jsx
import React, { useState } from "react";
import axios from "axios";
import { signInWithPopup } from "firebase/auth";
import { auth,googleProvider } from "@/Data/fireboase";

const FirebaseAuth = () => {
  const [loading, setLoading] = useState(false);

  const handleGoogleSignIn = async () => {
    setLoading(true);
    try {
      // 1. Popup Google login in browser
      const result = await signInWithPopup(auth, googleProvider);

      // 2. Obtain JWT ID token generated by Firebase
      const googleIdToken = await result.user.getIdToken();

      // 3. Send token to your backend API route
      const response = await axios.post("/api/v1/auth/google", {
        token: googleIdToken,
      });

      console.log("Backend response (User authenticated):", response.data);
    } catch (error) {
      console.error("Authentication Error:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button onClick={handleGoogleSignIn} disabled={loading}>
      {loading ? "Authenticating..." : "Sign in with Google"}
    </button>
  );
};

export default FirebaseAuth;